date:
  current_year: 2022

facebook:
  url: https://www.facebook.com/groups/8bitbunny
github:
  url: https://github.com/ramaboo/burn
redis:
  url: <%= ENV["REDIS_URL"] || "redis://127.0.0.1:6379" %>

